plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\A02443985\\Documents\\GitHub\\lro_dashboard\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build-only"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]